### PR TITLE
[CRB-137] Fix warnings, update to Rust 2018, and update dependencies

### PR DESCRIPTION
**Pull request by nathanwhit**
Split off from #4

### CODE REVIEW

**Review by atodorov — COMMENTED** [review]
I think this looks good but what bothers me is that there isn't a single automated test job here. Not even a simple compile/lint job which would give us some confidence in the changes.

**Review by CAGS295 — APPROVED** [review]

**Comment by CAGS295** [comment]
@will-gluwa 

> I think this looks good but what bothers me is that there isn't a single automated test job here. Not even a simple compile/lint job which would give us some confidence in the changes.

**Comment by ghost** [comment]
I agree. @atodorov please work with @nathanwhit to get some basic testing in place.

**Comment by atodorov** [comment]
> I agree. @atodorov please work with @nathanwhit to get some basic testing in place.

FTR that should be covered by CRB-147, CRB-51 and CRB-166 (#31) where I've had no luck so far to execute those tests inside GitHub Actions.

**Pull request merged**
