### PR TITLE
CRB-185 Fix CI and update transaction families

### PR DESCRIPTION
**Pull request by nathanwhit**
I had missed checking this crate in #28. This PR updates the dependencies to the latest versions and fixes the errors that caused CI to fail.

### CODE REVIEW

**Review by CAGS295 — APPROVED** [review]

**Comment by atodorov** [comment]
> I had missed checking this crate in #28. This PR updates the dependencies to the latest versions and fixes the errors that caused CI to fail.

Which CI jobs are you referring to b/c I don't see any links here or in #28? 

In the case of #31 being a no-go shouldn't we at least add a small GitHub job which tries and compiles the sources? I can push a commit to this PR if you agree.

**Comment by ghost** [comment]
> Which CI jobs are you referring to b/c I don't see any links here or in #28?

https://dev.azure.com/gluwa/Gluwa/_build/results?buildId=13456&view=results

There's additional discussion here also:
https://gluwa.slack.com/archives/C7JJP9WTF/p1631057711050500

**Comment by ghost** [comment]
> In the case of #31 being a no-go shouldn't we at least add a small GitHub job which tries and compiles the sources? I can push a commit to this PR if you agree.

I think this is a good idea. What are your thoughts @CAGS295 ?

**Comment by atodorov** [comment]
> > Which CI jobs are you referring to b/c I don't see any links here or in #28?
> 
> https://dev.azure.com/gluwa/Gluwa/_build/results?buildId=13456&view=results

The strange thing is that the status checks didn't appear at the bottom of the PR. Not for 28 at least.  For this one I can see the link to the test job in Azure, but yesterday when I commented I didn't see that. Maybe these jobs take some time and report their results afterwards, IDK. But that's another discussion, will open a ticket for it.

**Review by atodorov — APPROVED** [review]
LGTM but do you mind cherry-picking https://github.com/gluwa/Sawtooth-Core/pull/37/commits/d534386a46be8736f7e9a1b1ba0e1deff9b97811 as well.

**Pull request merged**
