### PR TITLE
[CRB-137] Fix warnings, update to 2018 Edition, resolve Clippy lints, apply fix to purge invalid txns, update deps

### PR DESCRIPTION
**Pull request by nathanwhit**

### CODE REVIEW

**Review by CAGS295 — APPROVED** [review]

**Comment by CAGS295** [comment]
Ideally, I would have liked changes to the batch injector and invalid txn purging as separate PRs.

**Comment by nathanwhit** [comment]
> 
> 
> Ideally, I would have liked changes to the batch injector and invalid txn purging as separate PRs.

I can split this PR up now and close this if you'd prefer, it wouldn't take me very long.

**Comment by CAGS295** [comment]
Please.

**Comment by nathanwhit** [comment]
Closed in favor of #28, #29, #30.

**Pull request closed without merging**
